# Generated by Django 3.2.16 on 2022-11-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.IntegerField(choices=[['Dem', 'Demandante'], ['Pro', 'Profesional'], ['Emp', 'Empresa'], ['Ong', 'ONG`S']]),
        ),
    ]
